### ISSUE TITLE
Unable to fully display long title

### ISSUE THREAD

**Issue by shelverizr** [amake/org_flutter#12]
```
#+TITLE: very loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong title
```

![Screenshot_2024-11-05-10-40-40-905_com madlonkay orgro](https://github.com/user-attachments/assets/a31d7998-0a95-4db3-9904-49ba3fe217b1)

**Comment by amake** [comment]
All "meta" lines (starting with `#+foo:`) do not line break and instead scroll horizontally. This is by design because they are usually not really part of the document content, but rather directives for how the content should behave or be processed. 

I will think about whether it's worth treating `#+title:` differently.

**Comment by shelverizr** [comment]
> All "meta" lines (starting with `#+foo:`) do not line break and instead scroll horizontally. This is by design because they are usually not really part of the document content, but rather directives for how the content should behave or be processed.
> 
> I will think about whether it's worth treating `#+title:` differently.

Please also consider `#+filetags`

**Comment by shelverizr** [comment]
> All "meta" lines (starting with `#+foo:`) do not line break and instead scroll horizontally. This is by design because they are usually not really part of the document content, but rather directives for how the content should behave or be processed.
> 
> I will think about whether it's worth treating `#+title:` differently.

Just tried it on Orgro, can't slide the title.

**Comment by amake** [comment]
Oops, you're right, I was thinking of something else to which I've given similar treatment.

Currently you can ensure that meta lines are not truncated by disabling Reader Mode in Orgro. If you are consuming org_flutter directly, you should provide an `OrgSettings` object with `deemphasizeMarkup` set to false (such as `OrgSettings.hideMarkup`).

**Comment by shelverizr** [comment]
> Oops, you're right, I was thinking of something else to which I've given similar treatment.
> 
> Currently you can ensure that meta lines are not truncated by disabling Reader Mode in Orgro. If you are consuming org_flutter directly, you should provide an `OrgSettings` object with `deemphasizeMarkup` set to false (such as `OrgSettings.hideMarkup`).

Tried disabling it. It's better.

**Comment by amake** [comment]
In org_flutter v7.10,

- "Document info" meta lines are styled like in Emacs, are never truncated, and are never de-emphasized. This includes `#+TITLE:`; see `M-x describe-face org-document-info-keyword`.
- Regular meta lines are scrollable when de-emphasized

**Comment by shelverizr** [comment]
> In org_flutter v7.10,
> 
> * "Document info" meta lines are styled like in Emacs, are never truncated, and are never de-emphasized. This includes `#+TITLE:`; see `M-x describe-face org-document-info-keyword`.
> * Regular meta lines are scrollable when de-emphasized

Tried it and it works fine. Thanks
