### ISSUE TITLE
Display ellipsis after headline if has content when folded

### ISSUE THREAD

**Issue by shelverizr** [amake/org_flutter#13]
Just like Emacs

![QQ截图20241115142117](https://github.com/user-attachments/assets/70e07e83-4d4d-4736-b6d3-c27297828e98)
![QQ截图20241115142128](https://github.com/user-attachments/assets/aea6911b-151d-45dc-9e34-07fcafa13244)

**Comment by shelverizr** [comment]
> Just like Emacs
> 
> ![QQ截图20241115142117](https://private-user-images.githubusercontent.com/16190857/386480811-70e07e83-4d4d-4736-b6d3-c27297828e98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTIwMzgsIm5iZiI6MTczMTY1MTczOCwicGF0aCI6Ii8xNjE5MDg1Ny8zODY0ODA4MTEtNzBlMDdlODMtNGQ0ZC00NzM2LWI2ZDMtYzI3Mjk3ODI4ZTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA2MjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOGViYWExNzI0YWU3ZjMxZmE1OGRhZjg2MjVkYTEzOTIwMzNjNzQ3YjZiM2Q4NDczNGE4YWNhMmJmNmZhNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Xf_fAoYw_QVFQG0k5wssQVz5oPlzfndaOjABgvPoIk) ![QQ截图20241115142128](https://private-user-images.githubusercontent.com/16190857/386480884-aea6911b-151d-45dc-9e34-07fcafa13244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTIwMzgsIm5iZiI6MTczMTY1MTczOCwicGF0aCI6Ii8xNjE5MDg1Ny8zODY0ODA4ODQtYWVhNjkxMWItMTUxZC00NWRjLTllMzQtMDdmY2FmYTEzMjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA2MjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMTZiYTg3OGY2ZGRjNmJkMTAyYjNlMTdkNmMwNjE2YjQ2MTkzZWNiNDE2M2ZiYmRhOTQ5NDdkOWI3NDdkNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mgc1jatTD7hKnqD_jynPyofvz-_1Sij4Gk1MBN1l4uI)

The advantage is that you can intuitively see whether there is content under the headline

**Comment by amake** [comment]
It should already be doing this, but I seem to have introduced a bug.
