### ISSUE TITLE
Titles with underlines in headline do not display as expected

### ISSUE THREAD

**Issue by shelverizr** [amake/org_flutter#14]
```
* shared_storage
* test_under
* _under
* t_u
```

![Screenshot_2024-11-21-09-24-56-062_com madlonkay orgro-edit](https://github.com/user-attachments/assets/a5edb8dd-9c49-4376-9e3e-f27ce76a72bb)

**Comment by amake** [comment]
This rendering is correct for when `org-pretty-entities` is non-nil (e.g. use `M-x org-toggle-pretty-entities`). 

To prevent this you can disable pretty entities in your document like

```org
#+STARTUP: entitiesplain
```

or

```org
# Local Variables:
# org-pretty-entities: nil
# End:
```

Or if you are consuming this library directly you can supply an OrgSettings with `prettyEntities: false`.

**Comment by amake** [comment]
To be clearer, you have accidentally used [subscript syntax](https://orgmode.org/org.html#Subscripts-and-Superscripts), and sub/superscript display is by default controlled by the same mechanism as entity prettification.

**Comment by shelverizr** [comment]
Can `org-use-sub-superscripts` be supported?

> You can set both org-use-sub-superscripts org-export-with-sub-superscripts in a file using the export option ‘^:’ (see [Export Settings](https://orgmode.org/org.html#Export-Settings)). For example, ‘#+OPTIONS: ^:{}’ sets the two options to {} and limits super- and subscripts to the curly bracket notation.

![20241121102702](https://github.com/user-attachments/assets/e2638bcd-7c7f-4263-84b2-a8b672548fc7)

**Comment by amake** [comment]
`org-use-sub-superscripts` and `org-pretty-entities-include-sub-superscripts` are supported in org_flutter 7.13.0. See also `OrgSettings.subSuperscripts` and `OrgSettings.strictSubSuperscripts`.

**Comment by shelverizr** [comment]
Works perfectly with `OrgSettings.strictSubSuperscripts`, thanks.
