### ISSUE TITLE
Hide/Render Org Mode Markup Syntax in Rendered Output

### ISSUE THREAD

**Issue by zikajk** [amake/org_flutter#9]
Certain Org markup symbols (e.g., ~, =) remain visible in the rendered output, potentially disrupting the clean visual representation. 
Proposal: extend the parsing logic to effectively conceal these markup symbols, while possibly introducing an option for devs who prefer to keep them visible.

**Comment by amake** [comment]
Does the [`hideMarkup` option](https://github.com/amake/org_flutter/blob/e88866ea6333f8f750b8207cba3e4804dbf43611/lib/org_flutter.dart#L151C15-L151C15) not do what you want?

It's not exposed as an option by default on the `Org` widget, but I could expose it. In the meantime the easy way to see the effect is with the `OrgText` widget, or in [Orgro](https://orgro.org/) where it's exposed in the UI as "Reader Mode".

**Comment by amake** [comment]
> Proposal: extend the parsing logic to effectively conceal these markup symbols

Hiding parts of markup is a presentation-layer concern, and shouldn't concern the parser (except as to require a certain level of granularity in the parse result such that unwanted symbols are easily distinguished from other results).

**Comment by zikajk** [comment]
It does, i wasn't aware of it, thank you. I will use the option once it will be exposed.

**Comment by zikajk** [comment]
> Does the [`hideMarkup` option](https://github.com/amake/org_flutter/blob/e88866ea6333f8f750b8207cba3e4804dbf43611/lib/org_flutter.dart#L151C15-L151C15) not do what you want?
> 
> 
> 
> It's not exposed as an option by default on the `Org` widget, but I could expose it. In the meantime the easy way to see the effect is with the `OrgText` widget, or in [Orgro](https://orgro.org/) where it's exposed in the UI as "Reader Mode".

It does, i wasn't aware of it, thank you.
- Edit: maybe 'OrgText' will be enough for my use case.

**Comment by amake** [comment]
I just published v4.4.0 which exposes `hideMarkup` as a parameter on `Org` and `OrgText`. It does more than just hide markup, though, so it might not fit your use case exactly.

**Comment by amake** [comment]
If you have specific additional needs, please open a new ticket.
